export const AGREEMENT_TEMPLATES = [
  {
    id: 'paid-work',
    name: 'Paid Work Agreement',
    category: 'compensation',
    description: 'For paid freelance or contract work on a project.',
    fields: [
      { id: 'projectTitle',     label: 'Project Title',       type: 'text',     placeholder: 'e.g. Hollow Reach', required: true },
      { id: 'ownerName',        label: 'Client / Owner Name', type: 'text',     placeholder: 'Full name or company', required: true },
      { id: 'collaboratorName', label: 'Contractor Name',     type: 'text',     placeholder: 'Full name', required: true },
      { id: 'role',             label: 'Role / Position',     type: 'text',     placeholder: 'e.g. 3D Artist', required: true },
      { id: 'paymentAmount',    label: 'Payment Amount',      type: 'number',   placeholder: '0.00', required: true },
      { id: 'currency',         label: 'Currency',            type: 'text',     placeholder: 'e.g. USD, GBP, EUR', required: true },
      { id: 'paymentSchedule',  label: 'Payment Schedule',    type: 'text',     placeholder: 'e.g. monthly / on delivery', required: true },
      { id: 'deliverables',     label: 'Deliverables',        type: 'textarea', placeholder: 'Describe what will be delivered', required: true },
      { id: 'startDate',        label: 'Start Date',          type: 'date',     placeholder: '', required: true },
      { id: 'endDate',          label: 'End Date',            type: 'date',     placeholder: '', required: true },
    ],
    body: `PAID WORK AGREEMENT

This Paid Work Agreement ("Agreement") is entered into as of {{startDate}} between {{ownerName}} ("Client") and {{collaboratorName}} ("Contractor").

1. PROJECT
The Contractor agrees to perform work on the project titled "{{projectTitle}}" in the capacity of {{role}}.

2. DELIVERABLES
The Contractor shall deliver the following:
{{deliverables}}

3. PAYMENT
The Client agrees to pay the Contractor {{currency}} {{paymentAmount}} per {{paymentSchedule}}. Payment shall be made upon satisfactory completion of agreed deliverables.

4. TERM
This Agreement commences on {{startDate}} and terminates on {{endDate}}, unless terminated earlier by either party with 14 days written notice.

5. INTELLECTUAL PROPERTY
All work product created by the Contractor under this Agreement shall be the sole property of the Client upon receipt of full payment.

6. CONFIDENTIALITY
The Contractor agrees to keep all project information confidential and not disclose it to third parties without the Client's prior written consent.

7. INDEPENDENT CONTRACTOR
The Contractor is an independent contractor, not an employee of the Client. The Contractor is solely responsible for their own taxes, insurance, and business expenses.

8. GOVERNING LAW
This Agreement shall be governed by applicable law in the jurisdiction of the parties. Any disputes shall be resolved through good-faith negotiation before any legal action is taken.

Both parties agree to the terms of this Agreement by their signatures below.`,
  },

  {
    id: 'revenue-share',
    name: 'Revenue Share Agreement',
    category: 'compensation',
    description: 'Split project revenue with a collaborator based on a percentage.',
    fields: [
      { id: 'projectTitle',       label: 'Project Title',          type: 'text',     placeholder: 'e.g. Hollow Reach', required: true },
      { id: 'ownerName',          label: 'Project Owner Name',     type: 'text',     placeholder: 'Full name', required: true },
      { id: 'collaboratorName',   label: 'Collaborator Name',      type: 'text',     placeholder: 'Full name', required: true },
      { id: 'role',               label: 'Collaborator Role',      type: 'text',     placeholder: 'e.g. Composer', required: true },
      { id: 'revenuePercentage',  label: 'Revenue Share (%)',      type: 'number',   placeholder: 'e.g. 15', required: true },
      { id: 'revenueTrigger',     label: 'Revenue Trigger',        type: 'text',     placeholder: 'e.g. first commercial sale', required: true },
      { id: 'paymentSchedule',    label: 'Payment Schedule',       type: 'text',     placeholder: 'e.g. quarterly', required: true },
      { id: 'projectDescription', label: 'Project Description',    type: 'textarea', placeholder: 'Brief description of the project', required: true },
      { id: 'startDate',          label: 'Start Date',             type: 'date',     placeholder: '', required: true },
    ],
    body: `REVENUE SHARE AGREEMENT

This Revenue Share Agreement ("Agreement") is entered into as of {{startDate}} between {{ownerName}} ("Project Owner") and {{collaboratorName}} ("Collaborator").

1. PROJECT
The parties agree to collaborate on "{{projectTitle}}": {{projectDescription}}. The Collaborator shall contribute in the capacity of {{role}}.

2. REVENUE SHARE
The Collaborator shall receive {{revenuePercentage}}% of net revenue generated by the project, beginning from {{revenueTrigger}}.

3. PAYMENT SCHEDULE
Revenue distributions shall be made {{paymentSchedule}}. The Project Owner shall provide transparent accounting of all revenue and expenses with each payment.

4. NET REVENUE DEFINED
"Net revenue" means gross revenue minus direct transaction costs including platform fees, payment processing fees, and refunds. General marketing and development costs are not deducted unless separately agreed in writing.

5. ACCOUNTING AND RECORDS
The Project Owner shall maintain accurate financial records and make them available to the Collaborator upon reasonable written request.

6. TERM
This Agreement commences on {{startDate}} and remains in effect for the commercial lifetime of the project unless terminated by mutual written agreement.

7. CONTRIBUTION OBLIGATIONS
The Collaborator agrees to fulfil their agreed role to a professional standard. Persistent failure to do so may result in renegotiation of the revenue share terms by mutual agreement.

8. INTELLECTUAL PROPERTY
Contributions made by the Collaborator are jointly owned under this Agreement. Upon any dissolution, ownership of specific assets shall be negotiated in a separate written agreement.

Both parties agree to the terms of this Agreement by their signatures below.`,
  },

  {
    id: 'volunteer',
    name: 'Volunteer / Passion Project Agreement',
    category: 'partnership',
    description: 'Formalise unpaid voluntary contributions with credit terms.',
    fields: [
      { id: 'projectTitle',       label: 'Project Title',         type: 'text',     placeholder: 'e.g. Hollow Reach', required: true },
      { id: 'ownerName',          label: 'Project Lead Name',     type: 'text',     placeholder: 'Full name', required: true },
      { id: 'collaboratorName',   label: 'Contributor Name',      type: 'text',     placeholder: 'Full name', required: true },
      { id: 'role',               label: 'Contributor Role',      type: 'text',     placeholder: 'e.g. Sound Designer', required: true },
      { id: 'projectDescription', label: 'Project Description',   type: 'textarea', placeholder: 'What is the project?', required: true },
      { id: 'timeCommitment',     label: 'Time Commitment',       type: 'text',     placeholder: 'e.g. ~5 hours per week', required: true },
      { id: 'startDate',          label: 'Start Date',            type: 'date',     placeholder: '', required: true },
      { id: 'creditName',         label: 'Credit As',             type: 'text',     placeholder: 'Name to appear in credits', required: true },
    ],
    body: `VOLUNTEER / PASSION PROJECT AGREEMENT

This Volunteer Agreement ("Agreement") is entered into as of {{startDate}} between {{ownerName}} ("Project Lead") and {{collaboratorName}} ("Volunteer Contributor").

1. PROJECT
This agreement covers voluntary contribution to "{{projectTitle}}": {{projectDescription}}. The Contributor will participate in the capacity of {{role}}.

2. VOLUNTARY NATURE
The Contributor acknowledges that their participation is entirely voluntary and no financial compensation is expected or promised. This is a passion project undertaken for creative fulfilment, skill development, and portfolio building purposes.

3. TIME COMMITMENT
The Contributor agrees to contribute approximately {{timeCommitment}} to the project. This is an estimate and may be adjusted by mutual agreement at any time.

4. CREDIT
The Contributor's work shall be credited as "{{creditName}}" in all public-facing credits, including in-game credits, project website, and promotional materials.

5. PORTFOLIO USE
The Contributor retains the right to display their work from this project in their personal portfolio, subject to the Project Lead's approval of what is shared publicly.

6. INTELLECTUAL PROPERTY
All contributions made to the project shall be jointly owned by all contributors unless a separate written agreement is signed.

7. GOOD FAITH
Both parties agree to participate in good faith and communicate openly. Either party may withdraw from the project with 7 days written notice.

8. NO LIABILITY
Neither party shall hold the other liable for losses arising from the voluntary and informal nature of this collaboration.

Both parties agree to the terms of this Agreement by their signatures below.`,
  },

  {
    id: 'grant-funding',
    name: 'Grant Funding Agreement',
    category: 'compensation',
    description: 'Document grant funds given for a specific project purpose.',
    fields: [
      { id: 'projectTitle',          label: 'Project Title',          type: 'text',     placeholder: 'e.g. Hollow Reach', required: true },
      { id: 'ownerName',             label: 'Grantor Name',           type: 'text',     placeholder: 'Organisation or person granting funds', required: true },
      { id: 'collaboratorName',      label: 'Recipient Name',         type: 'text',     placeholder: 'Full name or organisation', required: true },
      { id: 'grantAmount',           label: 'Grant Amount',           type: 'number',   placeholder: '0.00', required: true },
      { id: 'currency',              label: 'Currency',               type: 'text',     placeholder: 'e.g. USD, GBP', required: true },
      { id: 'grantPurpose',          label: 'Grant Purpose',          type: 'textarea', placeholder: 'What the grant will fund', required: true },
      { id: 'deliverables',          label: 'Deliverables',           type: 'textarea', placeholder: 'What the recipient will produce', required: true },
      { id: 'reportingRequirements', label: 'Reporting Requirements', type: 'textarea', placeholder: 'What reports must be submitted and when', required: true },
      { id: 'startDate',             label: 'Start Date',             type: 'date',     placeholder: '', required: true },
      { id: 'endDate',               label: 'End Date',               type: 'date',     placeholder: '', required: true },
    ],
    body: `GRANT FUNDING AGREEMENT

This Grant Funding Agreement ("Agreement") is entered into as of {{startDate}} between {{ownerName}} ("Grantor") and {{collaboratorName}} ("Recipient").

1. GRANT
The Grantor agrees to provide a grant of {{currency}} {{grantAmount}} to the Recipient for the project "{{projectTitle}}".

2. PURPOSE
The grant shall be used exclusively for:
{{grantPurpose}}

3. DELIVERABLES
The Recipient shall produce the following outputs:
{{deliverables}}

4. REPORTING
The Recipient shall provide the following reports to the Grantor:
{{reportingRequirements}}

5. TERM
The grant period runs from {{startDate}} to {{endDate}}. All grant funds must be utilised within this period unless an extension is agreed in writing.

6. FINANCIAL ACCOUNTABILITY
The Recipient shall maintain detailed records of all grant expenditure and make these available to the Grantor upon request. Unused funds must be returned at the end of the grant period.

7. INTELLECTUAL PROPERTY
Work created using grant funding shall be owned by the Recipient unless otherwise specified in this Agreement. The Grantor shall receive appropriate credit in all outputs produced with grant funds.

8. TERMINATION
The Grantor may terminate this Agreement and reclaim unspent funds if the Recipient fails to meet their obligations, provides false information, or misuses grant funds.

Both parties agree to the terms of this Agreement by their signatures below.`,
  },

  {
    id: 'nda',
    name: 'Non-Disclosure Agreement (NDA)',
    category: 'legal',
    description: 'Protect confidential project information shared with collaborators.',
    fields: [
      { id: 'disclosingParty',  label: 'Disclosing Party',            type: 'text',     placeholder: 'Name sharing the information', required: true },
      { id: 'receivingParty',   label: 'Receiving Party',             type: 'text',     placeholder: 'Name receiving the information', required: true },
      { id: 'projectTitle',     label: 'Project Name',                type: 'text',     placeholder: 'e.g. Hollow Reach', required: true },
      { id: 'confidentialInfo', label: 'Confidential Information',    type: 'textarea', placeholder: 'Describe what is considered confidential', required: true },
      { id: 'duration',         label: 'Duration of Confidentiality', type: 'text',     placeholder: 'e.g. 2 years from date of signing', required: true },
      { id: 'governingLaw',     label: 'Governing Law (Jurisdiction)',type: 'text',     placeholder: 'e.g. England and Wales', required: true },
    ],
    body: `NON-DISCLOSURE AGREEMENT

This Non-Disclosure Agreement ("Agreement") is entered into between {{disclosingParty}} ("Disclosing Party") and {{receivingParty}} ("Receiving Party") in connection with the project "{{projectTitle}}".

1. CONFIDENTIAL INFORMATION
"Confidential Information" means all non-public information disclosed by the Disclosing Party, including but not limited to:
{{confidentialInfo}}
...and any other information identified as confidential or that a reasonable person would understand to be confidential given the nature of the disclosure.

2. OBLIGATIONS OF THE RECEIVING PARTY
The Receiving Party agrees to:
(a) Hold all Confidential Information in strict confidence using at least the same degree of care it uses to protect its own confidential information;
(b) Not disclose any Confidential Information to any third party without prior written consent from the Disclosing Party;
(c) Use Confidential Information solely for the purpose of evaluating or working on "{{projectTitle}}"; and
(d) Limit internal access to Confidential Information to those individuals who genuinely need it.

3. EXCLUSIONS
These obligations do not apply to information that: (a) is or becomes publicly known through no fault of the Receiving Party; (b) was already rightfully known to the Receiving Party before disclosure; (c) is lawfully received from a third party without restriction; or (d) must be disclosed by law or court order.

4. TERM
This Agreement shall remain in effect for {{duration}} from the date it is signed by both parties.

5. RETURN OF INFORMATION
Upon written request from the Disclosing Party, the Receiving Party shall promptly return or permanently destroy all materials containing Confidential Information.

6. GOVERNING LAW
This Agreement shall be governed by and construed in accordance with the laws of {{governingLaw}}.

7. REMEDIES
The Receiving Party acknowledges that a breach of this Agreement may cause irreparable harm. The Disclosing Party shall be entitled to seek equitable relief including injunction without the need to prove actual damages.

Both parties agree to the terms of this Agreement by their signatures below.`,
  },

  {
    id: 'co-founder',
    name: 'Co-Founder Agreement',
    category: 'partnership',
    description: 'Define equity, roles and responsibilities between project co-founders.',
    fields: [
      { id: 'companyName',     label: 'Project / Company Name', type: 'text',     placeholder: 'e.g. Hollow Reach Studio', required: true },
      { id: 'founder1Name',    label: 'Founder 1 Full Name',   type: 'text',     placeholder: 'Full name', required: true },
      { id: 'founder2Name',    label: 'Founder 2 Full Name',   type: 'text',     placeholder: 'Full name', required: true },
      { id: 'equity1',         label: 'Founder 1 Equity (%)',  type: 'number',   placeholder: 'e.g. 50', required: true },
      { id: 'equity2',         label: 'Founder 2 Equity (%)',  type: 'number',   placeholder: 'e.g. 50', required: true },
      { id: 'roles',           label: 'Roles & Responsibilities', type: 'textarea', placeholder: 'Describe each founder\'s responsibilities', required: true },
      { id: 'vestingSchedule', label: 'Vesting Schedule',      type: 'textarea', placeholder: 'e.g. 4-year vest, 1-year cliff', required: true },
      { id: 'decisionMaking',  label: 'Decision Making',       type: 'textarea', placeholder: 'How are decisions made day-to-day vs major decisions?', required: true },
      { id: 'ipOwnership',     label: 'IP Ownership',          type: 'textarea', placeholder: 'Who owns IP brought into the project vs created during?', required: true },
      { id: 'startDate',       label: 'Agreement Date',        type: 'date',     placeholder: '', required: true },
    ],
    body: `CO-FOUNDER AGREEMENT

This Co-Founder Agreement ("Agreement") is entered into as of {{startDate}} between {{founder1Name}} and {{founder2Name}} regarding the project/company "{{companyName}}".

1. EQUITY SPLIT
{{founder1Name}} shall hold {{equity1}}% equity and {{founder2Name}} shall hold {{equity2}}% equity in {{companyName}}. The combined equity must equal 100%.

2. ROLES AND RESPONSIBILITIES
The founders agree to the following division of responsibilities:
{{roles}}

3. VESTING SCHEDULE
Equity shall vest according to the following schedule:
{{vestingSchedule}}
Unvested equity shall be forfeited if a founder voluntarily departs or is removed for cause.

4. DECISION MAKING
{{decisionMaking}}
All decisions involving fundraising, acquisition offers, dissolution, or changes to equity split require unanimous written consent of all founders.

5. INTELLECTUAL PROPERTY
{{ipOwnership}}
All intellectual property created in connection with {{companyName}} by either founder during the term of this Agreement shall be assigned to and owned by {{companyName}}.

6. FOUNDER DEPARTURE
In the event a founder wishes to leave, they must provide 30 days written notice. The departing founder retains vested equity only. Terms for any buyout of vested shares shall be negotiated in good faith at the time of departure.

7. CONFIDENTIALITY
Both founders agree to maintain confidentiality of all proprietary information related to {{companyName}} both during their involvement and for 2 years after departure.

8. AMENDMENTS
This Agreement may only be amended by written consent of all founders. Any amendments must be signed and dated.

Both parties agree to the terms of this Agreement by their signatures below.`,
  },

  {
    id: 'contractor',
    name: 'Contractor Agreement',
    category: 'compensation',
    description: 'Engage a contractor with defined scope, fees, and IP assignment.',
    fields: [
      { id: 'projectTitle',            label: 'Project Title',            type: 'text',     placeholder: 'e.g. Hollow Reach', required: true },
      { id: 'ownerName',               label: 'Client / Owner Name',      type: 'text',     placeholder: 'Full name or company', required: true },
      { id: 'contractorName',          label: 'Contractor Name',          type: 'text',     placeholder: 'Full name', required: true },
      { id: 'services',                label: 'Services',                 type: 'textarea', placeholder: 'Describe the services to be provided', required: true },
      { id: 'feeAmount',               label: 'Fee Amount',               type: 'number',   placeholder: '0.00', required: true },
      { id: 'currency',                label: 'Currency',                 type: 'text',     placeholder: 'e.g. USD, GBP', required: true },
      { id: 'paymentTerms',            label: 'Payment Terms',            type: 'text',     placeholder: 'e.g. 30 days from invoice', required: true },
      { id: 'intellectualPropertyClause', label: 'IP Clause',             type: 'textarea', placeholder: 'Who owns the IP created?', required: true },
      { id: 'startDate',               label: 'Start Date',               type: 'date',     placeholder: '', required: true },
      { id: 'endDate',                 label: 'End Date',                 type: 'date',     placeholder: '', required: true },
    ],
    body: `CONTRACTOR AGREEMENT

This Contractor Agreement ("Agreement") is entered into as of {{startDate}} between {{ownerName}} ("Client") and {{contractorName}} ("Contractor") for work on "{{projectTitle}}".

1. SERVICES
The Contractor shall provide the following services:
{{services}}

2. FEES
The Client shall pay the Contractor {{currency}} {{feeAmount}}. Payment terms: {{paymentTerms}}.

3. INTELLECTUAL PROPERTY
{{intellectualPropertyClause}}

4. TERM
This Agreement commences on {{startDate}} and terminates on {{endDate}}, unless extended or terminated earlier in writing.

5. INDEPENDENT CONTRACTOR STATUS
The Contractor is an independent contractor and not an employee, partner, or agent of the Client. The Contractor is solely responsible for their own taxes, national insurance contributions, and business expenses.

6. QUALITY OF WORK
The Contractor shall perform all services to a professional standard and in accordance with any written specifications provided by the Client.

7. REVISIONS
The Client may request reasonable revisions to delivered work. Revisions that materially exceed the original scope may be subject to additional fees, to be agreed in writing before work proceeds.

8. TERMINATION
Either party may terminate this Agreement with 14 days written notice. Upon termination, the Client shall pay for all work satisfactorily completed up to the termination date.

9. CONFIDENTIALITY
The Contractor agrees not to disclose any confidential information about the Client, the project, or the Client's business to any third party during or after the term of this Agreement.

Both parties agree to the terms of this Agreement by their signatures below.`,
  },

  {
    id: 'commission',
    name: 'Commission Agreement',
    category: 'compensation',
    description: 'Commission artwork or assets with defined deliverables and rights.',
    fields: [
      { id: 'projectTitle',          label: 'Project Title',          type: 'text',     placeholder: 'e.g. Hollow Reach', required: true },
      { id: 'ownerName',             label: 'Commissioner Name',      type: 'text',     placeholder: 'Full name', required: true },
      { id: 'artistName',            label: 'Artist Name',            type: 'text',     placeholder: 'Full name', required: true },
      { id: 'commissionDescription', label: 'Commission Description', type: 'textarea', placeholder: 'Describe what is being commissioned', required: true },
      { id: 'feeAmount',             label: 'Total Fee',              type: 'number',   placeholder: '0.00', required: true },
      { id: 'currency',              label: 'Currency',               type: 'text',     placeholder: 'e.g. USD, GBP', required: true },
      { id: 'revisions',             label: 'Revisions Included',     type: 'text',     placeholder: 'e.g. 2 rounds of revisions', required: true },
      { id: 'deliveryDate',          label: 'Delivery Date',          type: 'date',     placeholder: '', required: true },
      { id: 'rightsGranted',         label: 'Rights Granted',         type: 'textarea', placeholder: 'What rights does the Commissioner receive?', required: true },
    ],
    body: `COMMISSION AGREEMENT

This Commission Agreement ("Agreement") is entered into between {{ownerName}} ("Commissioner") and {{artistName}} ("Artist") for the project "{{projectTitle}}".

1. COMMISSION
The Artist agrees to create:
{{commissionDescription}}

2. FEE
The Commissioner shall pay the Artist {{currency}} {{feeAmount}} for the completed commission. Payment is structured as follows: 50% is due upon signing this Agreement as a non-refundable deposit; the remaining 50% is due upon delivery of final files.

3. REVISIONS
The commission includes {{revisions}} of revisions at no additional cost. Further revisions requested beyond this will be charged at the Artist's standard hourly rate, agreed in writing before commencing.

4. DELIVERY
The Artist shall deliver the completed commission by {{deliveryDate}}. The Artist shall notify the Commissioner in writing as soon as possible if this date cannot be met.

5. RIGHTS GRANTED
Upon receipt of full payment:
{{rightsGranted}}

6. ARTIST CREDIT
Unless otherwise agreed, the Artist retains the right to display this commission in their personal portfolio and social media as an example of their work.

7. CANCELLATION
If the Commissioner cancels after work has commenced, the deposit is non-refundable to cover work already completed. If the Artist cancels before delivery, the full deposit shall be refunded to the Commissioner.

8. FILE DELIVERY
The Artist shall deliver final files in industry-standard formats appropriate for the intended use, as agreed by both parties prior to commencing work.

Both parties agree to the terms of this Agreement by their signatures below.`,
  },
]
