// ===== HELPERS =====

export function downloadFile(filename, content, mimeType = 'text/plain') {
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

function stripHtml(html) {
  return (html || '').replace(/<[^>]*>/g, '').replace(/&nbsp;/g, ' ').replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>').trim()
}

export function htmlToMarkdown(html) {
  return (html || '')
    .replace(/<h[1-6][^>]*>(.*?)<\/h[1-6]>/gi, '## $1')
    .replace(/<strong>(.*?)<\/strong>/gi, '**$1**')
    .replace(/<em>(.*?)<\/em>/gi, '_$1_')
    .replace(/<u>(.*?)<\/u>/gi, '_$1_')
    .replace(/<li>(.*?)<\/li>/gi, '- $1')
    .replace(/<br\s*\/?>/gi, '\n')
    .replace(/<hr\s*\/?>/gi, '\n---\n')
    .replace(/<[^>]*>/g, '')
    .replace(/&nbsp;/g, ' ')
    .trim()
}

// ===== DIALOGUE EXPORTS =====

export function exportDialogueYarn(scenes, projectTitle) {
  let yarn = `title: ${projectTitle || 'Dialogue'}\ntags:\n---\n`

  scenes.forEach(scene => {
    yarn += `\n// Scene: ${scene.title}\n`
    yarn += `=== ${scene.title.replace(/\s+/g, '_')} ===\n`
    if (scene.location) yarn += `// Location: ${scene.location}\n`
    scene.lines?.forEach(line => {
      if (line.type === 'action') yarn += `// ${line.content}\n`
      else if (line.type === 'dialogue') yarn += `${line.speaker}: ${line.content}\n`
      else if (line.type === 'direction') yarn += `// (${line.content})\n`
    })
    yarn += `===\n`
  })

  yarn += `\n===`
  downloadFile(`${projectTitle}_dialogue.yarn`, yarn)
}

export function exportDialogueInk(scenes, projectTitle) {
  let ink = `// ${projectTitle} — Dialogue Export (Ink format)\n// Generated by HQ COMMAND\n\n`

  scenes.forEach(scene => {
    ink += `=== ${scene.title.replace(/\s+/g, '_').toLowerCase()} ===\n`
    if (scene.location) ink += `// Location: ${scene.location}\n`
    scene.lines?.forEach(line => {
      if (line.type === 'action') ink += `~ // ${line.content}\n`
      else if (line.type === 'dialogue') ink += `${line.speaker}: ${line.content}\n`
      else if (line.type === 'direction') ink += `// (${line.content})\n`
    })
    ink += `-> DONE\n\n`
  })

  downloadFile(`${projectTitle}_dialogue.ink`, ink)
}

export function exportDialogueCSV(scenes, projectTitle) {
  const rows = [['Scene', 'Location', 'Type', 'Speaker', 'Line', 'Node_ID']]

  scenes.forEach(scene => {
    scene.lines?.forEach((line, idx) => {
      rows.push([
        `"${scene.title}"`,
        `"${scene.location || ''}"`,
        `"${line.type}"`,
        `"${line.speaker || ''}"`,
        `"${(line.content || '').replace(/"/g, '""')}"`,
        `"${scene.title.replace(/\s+/g, '_')}_${idx}"`,
      ])
    })
  })

  downloadFile(`${projectTitle}_dialogue.csv`, rows.map(r => r.join(',')).join('\n'), 'text/csv')
}

export function exportDialogueFountain(scenes, projectTitle) {
  let fountain = `Title: ${projectTitle}\nCredit: Written by\nContact: Generated by HQ COMMAND\n\n`

  scenes.forEach(scene => {
    fountain += `\nINT. ${(scene.location || scene.title).toUpperCase()} - DAY\n\n`
    scene.lines?.forEach(line => {
      if (line.type === 'action') fountain += `${line.content}\n\n`
      else if (line.type === 'dialogue') fountain += `${line.speaker.toUpperCase()}\n${line.content}\n\n`
      else if (line.type === 'direction') fountain += `(${line.content})\n\n`
    })
  })

  downloadFile(`${projectTitle}_screenplay.fountain`, fountain)
}

export function exportDialoguePlainText(scenes, projectTitle) {
  let text = `${projectTitle.toUpperCase()}\nDIALOGUE SCRIPT\nGenerated by HQ COMMAND\n${'='.repeat(50)}\n\n`

  scenes.forEach(scene => {
    text += `SCENE: ${scene.title.toUpperCase()}\n`
    if (scene.location) text += `LOCATION: ${scene.location}\n`
    text += `${'-'.repeat(30)}\n\n`
    scene.lines?.forEach(line => {
      if (line.type === 'action') text += `${line.content}\n\n`
      else if (line.type === 'dialogue') text += `${line.speaker.toUpperCase()}\n  ${line.content}\n\n`
      else if (line.type === 'direction') text += `  (${line.content})\n\n`
    })
    text += '\n'
  })

  downloadFile(`${projectTitle}_script.txt`, text)
}

// ===== MECHANICS EXPORTS =====

export function exportMechanicsCSV(mechanics, projectTitle) {
  const rows = [['Name', 'Status', 'Description', 'Notes']]
  mechanics.forEach(m => {
    rows.push([
      `"${m.name}"`,
      `"${m.status}"`,
      `"${stripHtml(m.description).replace(/"/g, '""')}"`,
      `"${(m.notes || '').replace(/"/g, '""')}"`,
    ])
  })
  downloadFile(`${projectTitle}_mechanics.csv`, rows.map(r => r.join(',')).join('\n'), 'text/csv')
}

export function exportMechanicsMarkdown(mechanics, projectTitle) {
  let md = `# ${projectTitle} — Game Mechanics\n\n`
  const byStatus = {}
  mechanics.forEach(m => {
    if (!byStatus[m.status]) byStatus[m.status] = []
    byStatus[m.status].push(m)
  })

  Object.entries(byStatus).forEach(([status, items]) => {
    md += `## ${status}\n\n`
    items.forEach(m => {
      md += `### ${m.name}\n`
      md += `${htmlToMarkdown(m.description)}\n\n`
      if (m.notes) md += `> ${m.notes}\n\n`
    })
  })

  downloadFile(`${projectTitle}_mechanics.md`, md)
}

export function exportMechanicsJira(mechanics, projectTitle) {
  const tickets = mechanics.map(m => ({
    summary: m.name,
    description: stripHtml(m.description),
    status: m.status === 'Implemented' ? 'Done' : m.status === 'In Development' ? 'In Progress' : 'To Do',
    labels: ['mechanic', projectTitle.toLowerCase().replace(/\s+/g, '-')],
    priority: m.status === 'Planned' ? 'Medium' : 'High',
  }))

  downloadFile(`${projectTitle}_jira_import.json`, JSON.stringify(tickets, null, 2), 'application/json')
}

// ===== CHARACTER EXPORTS =====

export function exportCharactersMarkdown(characters, projectTitle) {
  let md = `# ${projectTitle} — Character Bible\n\nGenerated by HQ COMMAND\n\n---\n\n`

  characters.forEach(char => {
    md += `## ${char.name}\n\n`
    md += `**Role:** ${char.role || 'Unknown'}`
    if (char.age) md += ` | **Age:** ${char.age}`
    md += ` | **Status:** ${char.status || 'Active'}\n\n`
    if (char.appearance) md += `### Appearance\n${htmlToMarkdown(char.appearance)}\n\n`
    if (char.personality) md += `### Personality\n${htmlToMarkdown(char.personality)}\n\n`
    if (char.backstory) md += `### Backstory\n${htmlToMarkdown(char.backstory)}\n\n`
    if (char.motivations) md += `### Motivations\n${char.motivations}\n\n`
    if (char.fears) md += `### Fears\n${char.fears}\n\n`
    md += '---\n\n'
  })

  downloadFile(`${projectTitle}_characters.md`, md)
}

export function exportCharactersCSV(characters, projectTitle) {
  const rows = [['Name', 'Role', 'Age', 'Status', 'Motivations', 'Fears', 'Appearance', 'Backstory']]
  characters.forEach(c => {
    rows.push([
      `"${c.name}"`, `"${c.role || ''}"`, `"${c.age || ''}"`, `"${c.status || 'Active'}"`,
      `"${(c.motivations || '').replace(/"/g, '""')}"`,
      `"${(c.fears || '').replace(/"/g, '""')}"`,
      `"${stripHtml(c.appearance || '').replace(/"/g, '""')}"`,
      `"${stripHtml(c.backstory || '').replace(/"/g, '""')}"`,
    ])
  })
  downloadFile(`${projectTitle}_characters.csv`, rows.map(r => r.join(',')).join('\n'), 'text/csv')
}

// ===== WORLD BUILDING EXPORTS =====

export function exportWorldMarkdown(world, projectTitle) {
  let md = `# ${projectTitle} — World Bible\n\nGenerated by HQ COMMAND\n\n---\n\n`

  const sections = [
    { key: 'locations', title: 'Locations' },
    { key: 'factions', title: 'Factions' },
    { key: 'lore', title: 'Lore' },
    { key: 'rules', title: 'World Rules' },
  ]

  sections.forEach(({ key, title }) => {
    const items = world[key] || []
    if (!items.length) return
    md += `## ${title}\n\n`
    items.forEach(item => {
      md += `### ${item.name}\n`
      if (item.tags?.length) md += `*Tags: ${item.tags.join(', ')}*\n\n`
      md += `${htmlToMarkdown(item.description)}\n\n---\n\n`
    })
  })

  downloadFile(`${projectTitle}_world_bible.md`, md)
}

// ===== STORY ARCS EXPORT =====

export function exportArcsMarkdown(arcs, projectTitle) {
  let md = `# ${projectTitle} — Story Arcs\n\n`
  arcs.forEach(arc => {
    md += `## ${arc.title}\n`
    md += `**Status:** ${arc.status}\n\n`
    if (arc.summary) md += `${htmlToMarkdown(arc.summary)}\n\n`
    if (arc.beats?.length) {
      md += `### Story Beats\n\n`
      arc.beats.forEach((beat, i) => {
        md += `${i + 1}. **${beat.title}**\n   ${beat.description || ''}\n\n`
      })
    }
    md += '---\n\n'
  })
  downloadFile(`${projectTitle}_story_arcs.md`, md)
}

// ===== FULL GDD PDF =====

export function exportFullGDDPDF(project, gdd, storyStudio) {
  const mechanics = gdd?.sections?.mechanics || []
  const html = `<!DOCTYPE html><html><head><title>GDD — ${project.title}</title>
  <style>
    body { font-family: Georgia, serif; max-width: 800px; margin: 0 auto; padding: 40px; color: #111; }
    h1 { color: #534AB7; border-bottom: 3px solid #534AB7; padding-bottom: 12px; font-size: 28px; }
    h2 { color: #534AB7; margin-top: 40px; font-size: 20px; border-left: 4px solid #ed2793; padding-left: 12px; }
    h3 { color: #333; font-size: 16px; }
    .meta { color: #666; font-size: 13px; margin-bottom: 32px; }
    .section { margin-bottom: 36px; }
    .mechanic { padding: 12px; border: 1px solid #ddd; border-radius: 6px; margin-bottom: 10px; }
    .mechanic-status { display: inline-block; padding: 2px 8px; border-radius: 99px; font-size: 11px; font-weight: 600; }
    .character { padding: 16px; border: 1px solid #ddd; border-radius: 8px; margin-bottom: 16px; }
    hr { border: none; border-top: 1px solid #eee; margin: 24px 0; }
    @media print { body { padding: 20px; } h2 { page-break-before: always; } }
  </style></head><body>
  <h1>🎮 ${project.title}</h1>
  <h2 style="border:none;color:#ed2793;font-size:18px;">Game Design Document</h2>
  <div class="meta">Generated ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })} · HQ COMMAND</div>

  ${gdd?.sections?.vision?.content ? `<div class="section"><h2>🎯 Vision Statement</h2>${gdd.sections.vision.content}</div>` : ''}
  ${gdd?.sections?.coreLoop?.content ? `<div class="section"><h2>🔄 Core Loop</h2>${gdd.sections.coreLoop.content}</div>` : ''}

  ${mechanics.length ? `<div class="section"><h2>⚙️ Mechanics</h2>
    ${mechanics.filter(m => m.status !== 'Cut').map(m => `
      <div class="mechanic">
        <strong>${m.name}</strong>
        <span class="mechanic-status" style="background:${m.status === 'Implemented' ? '#dcfce7' : m.status === 'In Development' ? '#ede9fe' : '#fef9c3'}">${m.status}</span>
        <p>${stripHtml(m.description)}</p>
      </div>
    `).join('')}
  </div>` : ''}

  ${gdd?.sections?.story?.content ? `<div class="section"><h2>📖 Story &amp; Setting</h2>${gdd.sections.story.content}</div>` : ''}
  ${gdd?.sections?.artDirection?.content ? `<div class="section"><h2>🎨 Art Direction</h2>${gdd.sections.artDirection.content}</div>` : ''}
  ${gdd?.sections?.audioDirection?.content ? `<div class="section"><h2>🔊 Audio Direction</h2>${gdd.sections.audioDirection.content}</div>` : ''}
  ${gdd?.sections?.platform?.content ? `<div class="section"><h2>📱 Platform &amp; Technical</h2>${gdd.sections.platform.content}</div>` : ''}
  ${gdd?.sections?.audience?.content ? `<div class="section"><h2>👥 Target Audience</h2>${gdd.sections.audience.content}</div>` : ''}
  ${gdd?.sections?.scope?.content ? `<div class="section"><h2>📊 Scope &amp; Constraints</h2>${gdd.sections.scope.content}</div>` : ''}

  ${storyStudio?.characters?.length ? `<div class="section"><h2>👤 Characters</h2>
    ${storyStudio.characters.map(c => `
      <div class="character">
        <h3>${c.name} <span style="font-weight:normal;font-size:13px;color:#666">${c.role || ''}</span></h3>
        ${c.motivations ? `<p><strong>Motivations:</strong> ${c.motivations}</p>` : ''}
        ${c.backstory ? `<p><strong>Backstory:</strong> ${stripHtml(c.backstory)}</p>` : ''}
      </div>
    `).join('')}
  </div>` : ''}

  </body></html>`

  const win = window.open('', '_blank')
  if (!win) { alert('Pop-up blocked — please allow pop-ups for this site.'); return }
  win.document.write(html)
  win.document.close()
  setTimeout(() => win.print(), 500)
}

// ===== FULL GDD MARKDOWN =====

export function exportFullGDDMarkdown(project, gdd, storyStudio) {
  let md = `# ${project.title} — Game Design Document\n\n`
  md += `*Generated by HQ COMMAND on ${new Date().toLocaleDateString('en-GB')}*\n\n---\n\n`

  const textSections = [
    { key: 'vision',         emoji: '🎯', title: 'Vision Statement' },
    { key: 'coreLoop',       emoji: '🔄', title: 'Core Loop' },
    { key: 'story',          emoji: '📖', title: 'Story & Setting' },
    { key: 'artDirection',   emoji: '🎨', title: 'Art Direction' },
    { key: 'audioDirection', emoji: '🔊', title: 'Audio Direction' },
    { key: 'platform',       emoji: '📱', title: 'Platform & Technical' },
    { key: 'audience',       emoji: '👥', title: 'Target Audience' },
    { key: 'scope',          emoji: '📊', title: 'Scope & Constraints' },
  ]

  textSections.forEach(({ key, emoji, title }) => {
    const content = gdd?.sections?.[key]?.content
    if (!content) return
    md += `## ${emoji} ${title}\n\n${htmlToMarkdown(content)}\n\n---\n\n`
  })

  const mechanics = gdd?.sections?.mechanics || []
  if (mechanics.length) {
    md += `## ⚙️ Mechanics\n\n`
    mechanics.forEach(m => {
      md += `### ${m.name} \`${m.status}\`\n${htmlToMarkdown(m.description)}\n\n`
    })
    md += '---\n\n'
  }

  downloadFile(`${project.title}_GDD.md`, md)
}
