export function generateInvoice(project, transactions, currency, ownerUser) {
  const expenses = transactions.filter(t => t.type === 'expense')
  const income = transactions.filter(t => t.type === 'income')
  const totalExpenses = expenses.reduce((sum, t) => sum + Number(t.amount), 0)
  const totalIncome = income.reduce((sum, t) => sum + Number(t.amount), 0)
  const net = totalIncome - totalExpenses

  const currencySymbol = { GBP: '£', USD: '$', EUR: '€', AUD: 'A$' }[currency] || currency
  const date = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })
  const invoiceNumber = `HQCMD-${Date.now().toString().slice(-6)}`

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>Invoice — ${project.title}</title>
      <style>
        body { font-family: Arial, sans-serif; color: #111; max-width: 800px; margin: 0 auto; padding: 40px; }
        .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 40px; border-bottom: 3px solid #534AB7; padding-bottom: 20px; }
        .logo { font-size: 24px; font-weight: 700; color: #534AB7; }
        .invoice-details { text-align: right; font-size: 13px; color: #666; }
        .invoice-number { font-size: 18px; font-weight: 700; color: #111; }
        h2 { color: #534AB7; font-size: 14px; text-transform: uppercase; letter-spacing: 0.1em; margin: 24px 0 8px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 24px; }
        th { background: #f5f5f5; padding: 10px 12px; text-align: left; font-size: 12px; text-transform: uppercase; color: #666; border-bottom: 1px solid #ddd; }
        td { padding: 10px 12px; border-bottom: 1px solid #eee; font-size: 13px; }
        .amount { text-align: right; font-weight: 500; }
        .expense { color: #dc2626; }
        .income { color: #16a34a; }
        .totals { margin-top: 24px; border-top: 2px solid #534AB7; padding-top: 16px; }
        .total-row { display: flex; justify-content: space-between; padding: 6px 0; font-size: 14px; }
        .total-row.net { font-weight: 700; font-size: 16px; color: ${net >= 0 ? '#16a34a' : '#dc2626'}; border-top: 1px solid #ddd; margin-top: 8px; padding-top: 12px; }
        .footer { margin-top: 48px; padding-top: 20px; border-top: 1px solid #eee; font-size: 11px; color: #999; text-align: center; }
        .disclaimer { margin-top: 16px; padding: 12px; background: #fff8e1; border: 1px solid #f59e0b; border-radius: 6px; font-size: 11px; color: #92400e; }
        @media print { body { padding: 20px; } }
      </style>
    </head>
    <body>
      <div class="header">
        <div>
          <div class="logo">HQ:CMD</div>
          <div style="font-size:13px;color:#666;margin-top:4px">Project Budget Report</div>
        </div>
        <div class="invoice-details">
          <div class="invoice-number">${invoiceNumber}</div>
          <div>Date: ${date}</div>
          <div>Project: ${project.title}</div>
          ${ownerUser ? `<div>Owner: ${ownerUser.name}</div>` : ''}
        </div>
      </div>

      <div class="disclaimer">
        ⚠ This document is a budget summary generated by HQ COMMAND. It is not a legally binding invoice. For formal invoicing, please consult an accountant or use dedicated invoicing software.
      </div>

      ${income.length > 0 ? `
      <h2>Income</h2>
      <table>
        <thead><tr><th>Date</th><th>Description</th><th>Category</th><th class="amount">Amount</th></tr></thead>
        <tbody>
          ${income.map(t => `
            <tr>
              <td>${t.date || '—'}</td>
              <td>${t.description}</td>
              <td>${t.category || '—'}</td>
              <td class="amount income">+${currencySymbol}${Number(t.amount).toFixed(2)}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>` : ''}

      ${expenses.length > 0 ? `
      <h2>Expenses</h2>
      <table>
        <thead><tr><th>Date</th><th>Description</th><th>Category</th><th class="amount">Amount</th></tr></thead>
        <tbody>
          ${expenses.map(t => `
            <tr>
              <td>${t.date || '—'}</td>
              <td>${t.description}</td>
              <td>${t.category || '—'}</td>
              <td class="amount expense">-${currencySymbol}${Number(t.amount).toFixed(2)}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>` : ''}

      <div class="totals">
        <div class="total-row"><span>Total Income</span><span style="color:#16a34a">+${currencySymbol}${totalIncome.toFixed(2)}</span></div>
        <div class="total-row"><span>Total Expenses</span><span style="color:#dc2626">-${currencySymbol}${totalExpenses.toFixed(2)}</span></div>
        <div class="total-row net"><span>Net Balance</span><span>${net >= 0 ? '+' : ''}${currencySymbol}${net.toFixed(2)}</span></div>
      </div>

      <div class="footer">
        Generated by HQ COMMAND · hqcmd.vercel.app · ${date}<br>
        This is a budget summary only and does not constitute a formal invoice or financial advice.
      </div>
    </body>
    </html>
  `

  const win = window.open('', '_blank')
  win.document.write(html)
  win.document.close()
  win.focus()
  setTimeout(() => win.print(), 500)
}
