export const PROJECT_TEMPLATES = [
  {
    id: 'solo_indie',
    name: 'Solo Indie Game',
    emoji: '🎮',
    description: 'A single developer with freelance collaborators. Great for your first commercial project.',
    category: 'Game Development',
    timeline: '12 months',
    commitment: 'Flexible',
    compensation: 'Revenue Share',
    rolesNeeded: ['Artist', 'Composer', 'QA Tester', 'Marketing'],
    milestones: [
      { name: 'Concept & Design', date: null, completed: false },
      { name: 'Prototype', date: null, completed: false },
      { name: 'Alpha', date: null, completed: false },
      { name: 'Beta', date: null, completed: false },
      { name: 'Launch', date: null, completed: false },
    ],
    tags: ['indie', 'solo', 'commercial'],
  },
  {
    id: 'game_jam',
    name: 'Game Jam Project',
    emoji: '🏁',
    description: 'Fast and focused. Built for 48-72 hour game jams with a small tight-knit team.',
    category: 'Game Development',
    timeline: '3 days',
    commitment: 'Full-time',
    compensation: 'Passion Project',
    rolesNeeded: ['Programmer', 'Artist', 'Composer'],
    milestones: [
      { name: 'Concept Lock', date: null, completed: false },
      { name: 'Core Mechanic Working', date: null, completed: false },
      { name: 'Art & Audio Pass', date: null, completed: false },
      { name: 'Polish & Submit', date: null, completed: false },
    ],
    tags: ['jam', 'fast', 'passion'],
  },
  {
    id: 'studio_collab',
    name: 'Studio Collaboration',
    emoji: '🤝',
    description: 'A full team project with defined roles, agreements, and a structured production pipeline.',
    category: 'Game Development',
    timeline: '18 months',
    commitment: 'Part-time',
    compensation: 'Revenue Share',
    rolesNeeded: ['Lead Programmer', 'Lead Artist', 'Game Designer', 'Composer', 'QA Lead', 'Producer'],
    milestones: [
      { name: 'Pre-Production', date: null, completed: false },
      { name: 'Production Start', date: null, completed: false },
      { name: 'Alpha Build', date: null, completed: false },
      { name: 'Beta Build', date: null, completed: false },
      { name: 'Gold Master', date: null, completed: false },
      { name: 'Launch', date: null, completed: false },
    ],
    tags: ['studio', 'team', 'full production'],
  },
  {
    id: 'mobile_game',
    name: 'Mobile Game',
    emoji: '📱',
    description: 'Designed for iOS and Android releases. Includes store submission and UA milestones.',
    category: 'Game Development',
    timeline: '6 months',
    commitment: 'Part-time',
    compensation: 'Revenue Share',
    rolesNeeded: ['Mobile Developer', 'UI Artist', 'Game Designer', 'Marketing'],
    milestones: [
      { name: 'Game Design Document', date: null, completed: false },
      { name: 'Core Loop Complete', date: null, completed: false },
      { name: 'Content Complete', date: null, completed: false },
      { name: 'QA & Testing', date: null, completed: false },
      { name: 'Store Submission', date: null, completed: false },
      { name: 'Launch & UA', date: null, completed: false },
    ],
    tags: ['mobile', 'ios', 'android'],
  },
  {
    id: 'learning_project',
    name: 'Learning Project',
    emoji: '🎓',
    description: 'Your first game! Low pressure, focused on learning. Great for getting started.',
    category: 'Game Development',
    timeline: '3 months',
    commitment: 'Flexible',
    compensation: 'Passion Project',
    rolesNeeded: ['Mentor', 'QA Tester'],
    milestones: [
      { name: 'Pick Your Engine', date: null, completed: false },
      { name: 'First Mechanic Working', date: null, completed: false },
      { name: 'First Playable Level', date: null, completed: false },
      { name: 'Game Complete', date: null, completed: false },
    ],
    tags: ['beginner', 'learning', 'first game'],
  },
  {
    id: 'narrative_game',
    name: 'Narrative / Visual Novel',
    emoji: '📖',
    description: 'Story-driven experience with branching dialogue, art, and music.',
    category: 'Game Development',
    timeline: '9 months',
    commitment: 'Part-time',
    compensation: 'Revenue Share',
    rolesNeeded: ['Writer', 'Narrative Designer', 'Artist', 'Composer', 'Programmer'],
    milestones: [
      { name: 'Story Bible Complete', date: null, completed: false },
      { name: 'Script Draft 1', date: null, completed: false },
      { name: 'Art Style Locked', date: null, completed: false },
      { name: 'Chapter 1 Complete', date: null, completed: false },
      { name: 'Full Game Complete', date: null, completed: false },
      { name: 'Launch', date: null, completed: false },
    ],
    tags: ['narrative', 'visual novel', 'story'],
  },
]
